name 'flannel'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures flannel'
long_description 'Installs/Configures flannel'
version '0.1.0'
